const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),esbuild=require('esbuild');
const {chromium}=require('playwright');
(async()=>{const root=path.resolve(__dirname,'..'),out=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'delivery-test-')),'fixture.js');
await esbuild.build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import Workspace from './src/delivery/DeliveryWorkspace.jsx';createRoot(document.getElementById('root')).render(<Workspace role="OWNER"/>);`,resolveDir:root,loader:'jsx'},outfile:out,bundle:true,format:'iife',loader:{'.css':'empty'},plugins:[{name:'offline',setup(b){b.onResolve({filter:/auth\/session.js$/},()=>({path:'session',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const CORE_API="http://delivery.test";export const readSessionToken=()=>"synthetic";',loader:'js'}));}}]});
const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));let saved;
const pkg={document:{id:1,site:'MAJA',serviceDate:'2026-10-05',documentNumber:'220/BB/MMD/X/2026',documentType:'BAHAN_BAKU',status:'FINAL',total:25000,items:[{itemName:'Beras',quantity:2,unit:'kg',unitPrice:12500,lineTotal:25000}],header:{issuerName:'Vendor Uji'}},numbers:{PO:'PO/2026/X/001',SJ:'SJ/202610/001',CKL:'CKL/202610/001',KUI:'001/KUI.Banper/BB/X/2026'},dates:{PO:'2026-10-03',SJ:'2026-10-04',CKL:'2026-10-04',KUI:'2026-10-06'},settings:{stamp:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==',signature:'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg=='}};
await page.route('**/*',r=>{const url=r.request().url();if(url.includes('/v1/')){if(/\/accountant-documents\/2$/.test(url))return r.fulfill({contentType:'application/json',body:JSON.stringify({document:{...pkg.document,id:2,documentNumber:'221/BB/MMD/X/2026'}})});if(r.request().method()==='PUT')saved=r.request().postDataJSON();return r.fulfill({contentType:'application/json',body:JSON.stringify(url.includes('delivery-sync')?{packages:[pkg,{...pkg,document:{...pkg.document,id:2,documentNumber:'221/BB/MMD/X/2026'}}]}:{ok:true})});}return r.fulfill({contentType:'text/html',body:`<meta name="viewport" content="width=device-width,initial-scale=1"><style>${fs.readFileSync(path.join(root,'src/delivery/delivery.css'),'utf8')}</style><div id="root"></div>`});});
await page.goto('http://delivery.test/delivery?site=MAJA&date=2026-10-05');await page.addScriptTag({path:out});await page.addStyleTag({content:fs.readFileSync(path.join(root,'src/delivery/delivery-preview.css'),'utf8')});await page.getByRole('button',{name:/220\/BB/}).click();
await page.getByRole('dialog',{name:'Preview Dokumen Pendamping'}).waitFor();
const frame=page.frameLocator('iframe[title="Preview cetak editable"]');
await frame.getByRole('heading',{name:'SURAT JALAN',exact:true}).waitFor();
await page.getByRole('tab',{name:'Kuitansi',exact:true}).click();
await frame.getByRole('heading',{name:'K U I T A N S I',exact:true}).waitFor();
await frame.locator('.toolbar').waitFor({state:'hidden'});
await frame.locator('.title').click();await page.keyboard.press('End');await page.keyboard.type(' EDIT CETAK');
assert.ok((await frame.locator('.paper').textContent()).includes('EDIT CETAK'));
for(const width of [360,768,904,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);}
await page.route('**/v1/accountant-documents/1',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({document:pkg.document})}));
await page.evaluate(()=>{const frame=document.querySelector('iframe');frame.contentWindow.print=()=>{window.testPrinted=frame.contentDocument.querySelector('.paper').textContent;};});
await page.getByRole('button',{name:'Cetak / Simpan PDF',exact:true}).click();
await page.waitForFunction(()=>window.testPrinted?.includes('EDIT CETAK'));
await frame.locator('.sign-space [data-asset="signature"]').evaluate(el=>{el.style.left='50px';el.style.top='20px';el.style.width='100px';});page.on('dialog',d=>d.accept());const positionSaved=page.waitForResponse(r=>r.url().includes('/delivery-profiles/KUI'));await page.getByRole('button',{name:'Simpan posisi TTD/stempel'}).click();await positionSaved;assert.equal(saved.settings.positionLayoutVersion,2);assert.equal(saved.settings.positions.signature.x,50);
await page.screenshot({path:path.join(root,'../delivery-preview-qa.png')});
await page.getByRole('button',{name:'Edit identitas & aset',exact:true}).click();
await page.getByLabel('Nama yayasan / kop BGN').fill('Yayasan Uji');await page.getByRole('button',{name:'Simpan master jenis surat'}).click();await page.waitForFunction(()=>!document.body.textContent.includes('Memuat / menyimpan'));assert.equal(saved.settings.foundation,'Yayasan Uji');
await page.getByRole('button',{name:'Daftar',exact:true}).click();assert.equal(await page.locator('.delivery-list .delivery-card').count(),2);
await page.getByRole('button',{name:'Nota Pesanan',exact:true}).click();await page.getByLabel('Nama yayasan / kop BGN').fill('Yayasan PO saja');await page.getByRole('button',{name:'Simpan master jenis surat'}).click();await page.waitForFunction(()=>!document.body.textContent.includes('Memuat / menyimpan'));
await page.getByRole('button',{name:'Surat Jalan',exact:true}).click();assert.equal(await page.getByLabel('Nama yayasan / kop BGN').inputValue(),'Yayasan Uji');
await page.getByRole('checkbox',{name:'Pilih 220/BB/MMD/X/2026',exact:true}).check();
await page.getByRole('checkbox',{name:'Pilih 221/BB/MMD/X/2026',exact:true}).check();await page.getByRole('checkbox',{name:'Nota Pesanan',exact:true}).check();await page.getByRole('checkbox',{name:'Kuitansi',exact:true}).check();
const popupPromise=page.waitForEvent('popup');await page.getByRole('button',{name:'Preview & cetak terpilih'}).click();const popup=await popupPromise;await popup.locator('.paper').first().waitFor();assert.equal(await popup.locator('.paper').count(),6);assert.ok((await popup.locator('.paper').first().textContent()).includes('Beras'));assert.equal(await popup.locator('.paper').nth(2).locator('.sign-space [data-asset="signature"]').evaluate(el=>el.style.left),'50px');await popup.screenshot({path:path.join(root,'../delivery-bulk-qa.png'),fullPage:true});await popup.close();
for(const width of [360,768,904,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true,`no overflow ${width}`);}
assert.deepEqual(errors,[]);console.log('PASS delivery calendar/list, editable saved settings and mobile/Fold widths');
const stampBuffer=Buffer.alloc(5*1024*1024);Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aWQAAAABJRU5ErkJggg==','base64').copy(stampBuffer);
const stampInput=page.locator('.delivery-master-editor input[type="file"]').nth(2);
await stampInput.setInputFiles({name:'stamp.png',mimeType:'image/png',buffer:stampBuffer});await page.locator('.delivery-master-editor img[alt="Stempel pengirim / penerima uang"]').waitFor();
await page.getByRole('button',{name:'Simpan master jenis surat'}).click();await page.waitForFunction(()=>!document.body.textContent.includes('Memuat / menyimpan'));assert.ok(saved.settings.stamp.length>6900000);
await stampInput.setInputFiles({name:'too-large.png',mimeType:'image/png',buffer:Buffer.alloc(5*1024*1024+1)});await page.getByRole('alert').filter({hasText:'maksimal 5 MB'}).waitFor();assert.equal(await page.locator('.delivery-master-editor img[alt="Stempel pengirim / penerima uang"]').count(),1);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});

