const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),esbuild=require('esbuild');
const{chromium}=require('playwright');
(async()=>{const root=path.resolve(__dirname,'..'),out=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'recap-test-')),'fixture.js');
await esbuild.build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import Recap from './src/lpdh/InvoiceRecap.jsx';createRoot(document.getElementById('root')).render(<Recap site="CEMPLANG" onOpen={d=>window.openedDate=d}/>);`,resolveDir:root,loader:'jsx'},outfile:out,bundle:true,format:'iife',plugins:[{name:'offline',setup(b){b.onResolve({filter:/auth\/session.js$/},()=>({path:'session',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const CORE_API="http://recap.test";export const readSessionToken=()=>"synthetic";',loader:'js'}));}}]});
const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();let params;
await page.route('**/*',r=>{if(r.request().url().includes('/v1/')){params=new URL(r.request().url()).searchParams;return r.fulfill({contentType:'application/json',body:JSON.stringify({documents:[{id:1,documentNumber:'1/BB/X/2026',documentType:'BAHAN_BAKU',serviceDate:params.get('start_date'),status:'FINAL',total:100000},{id:2,documentNumber:'2/BB/X/2026',documentType:'BAHAN_BAKU',serviceDate:params.get('start_date'),status:'CANCELLED',total:900000}]})});}return r.fulfill({contentType:'text/html',body:'<meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div>'});});
await page.goto('http://recap.test');await page.addScriptTag({path:out});await page.addStyleTag({content:fs.readFileSync(path.join(root,'src/lpdh/lpdh.css'),'utf8')});await page.getByText('Total FINAL',{exact:false}).last().waitFor();await page.locator('.invoice-recap-card').first().waitFor();assert.equal(params.get('site'),'CEMPLANG');assert.equal(new Date(params.get('start_date')+'T12:00:00').getDay(),1);assert.equal(new Date(params.get('end_date')+'T12:00:00').getDay(),5);assert.equal(await page.locator('.invoice-recap-calendar>section').count(),5);assert.ok((await page.locator('section').first().innerText()).includes('Total FINAL Rp 100.000'));await page.getByRole('button',{name:'List',exact:true}).click();assert.equal(await page.locator('.invoice-recap-list .invoice-recap-card').count(),2);await page.locator('.invoice-recap-card').first().click();assert.equal(await page.evaluate(()=>window.openedDate),params.get('start_date'));
await page.getByLabel('Rekap dari tanggal').fill('2026-09-28');await page.getByLabel('Rekap sampai tanggal').fill('2026-10-09');await page.locator('.invoice-recap-card').first().waitFor();assert.equal(params.get('start_date'),'2026-09-28');assert.equal(params.get('end_date'),'2026-10-09');
await page.getByRole('button',{name:'Kalender',exact:true}).click();for(const width of [360,768,904,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);}console.log('PASS weekly dates, range/site filters, totals excluding cancelled, list/calendar, navigation and responsive widths');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});

