const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),esbuild=require('esbuild');
const{chromium}=require('playwright');
(async()=>{const root=path.resolve(__dirname,'..'),out=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'recap-test-')),'fixture.js');
await esbuild.build({stdin:{contents:`import React from 'react';import{createRoot}from'react-dom/client';import Recap from './src/lpdh/InvoiceRecap.jsx';createRoot(document.getElementById('root')).render(<Recap site="CEMPLANG"/>);`,resolveDir:root,loader:'jsx'},outfile:out,bundle:true,format:'iife',plugins:[{name:'offline',setup(b){b.onResolve({filter:/auth\/session.js$/},()=>({path:'session',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const CORE_API="http://recap.test";export const readSessionToken=()=>"synthetic";',loader:'js'}));}}]});
const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();let params;
await page.route('**/*',r=>{const url=r.request().url();if(url.includes('/v1/')){if(url.endsWith('/pdf'))return r.fulfill({contentType:'application/json',body:JSON.stringify({filename:'test.pdf',mimeType:'application/pdf',contentBase64:Buffer.from('%PDF-1.4 test').toString('base64')})});params=new URL(url).searchParams;const date=params.get('start_date');return r.fulfill({contentType:'application/json',body:JSON.stringify({documents:[{id:1,documentNumber:'1/BB/X/2026',documentType:'BAHAN_BAKU',serviceDate:date,status:'FINAL',total:100000,driveUri:'https://drive.google.com/file/d/test/view',driveExcelUri:'https://drive.google.com/file/d/excel/view',items:[]},{id:2,documentNumber:'2/BB/X/2026',documentType:'BAHAN_BAKU',serviceDate:date,status:'CANCELLED',total:900000},{id:3,documentNumber:'3/OP/X/2026',documentType:'UPAH_RELAWAN',serviceDate:date,status:'FINAL',total:300,items:[{itemName:'Relawan',lineTotal:100,metadata:{recipientType:'Relawan'}},{itemName:'Guru',lineTotal:50,metadata:{recipientType:'Guru'}},{itemName:'Kader',lineTotal:150,metadata:{recipientType:'Kader'}}]}]})});}return r.fulfill({contentType:'text/html',body:'<meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div>'});});
await page.goto('http://recap.test');await page.addScriptTag({path:out});await page.addStyleTag({content:fs.readFileSync(path.join(root,'src/lpdh/lpdh.css'),'utf8')});await page.locator('.invoice-recap-table tbody tr').first().waitFor();assert.equal(params.get('site'),'CEMPLANG');assert.equal(new Date(params.get('start_date')+'T12:00:00').getDay(),1);assert.equal(new Date(params.get('end_date')+'T12:00:00').getDay(),5);assert.equal(await page.locator('.invoice-recap-calendar>section').count(),5);assert.equal(await page.locator('.invoice-recap-table tbody tr').count(),2);assert.ok((await page.locator('.invoice-recap-table tfoot').innerText()).includes('Rp 100.300'));
const totals=await page.locator('.invoice-recap-totals').innerText();assert.ok(totals.includes('Rp 100')&&totals.includes('Rp 50')&&totals.includes('Rp 150'));
await page.getByRole('checkbox',{name:'Pilih rekap 3/OP/X/2026 3'}).check();assert.ok((await page.locator('.invoice-recap-table tfoot').innerText()).endsWith('Rp 300'));await page.getByRole('button',{name:'Hapus ceklis',exact:true}).click();await page.getByRole('button',{name:'List / Tabel',exact:true}).click();assert.equal(await page.locator('.invoice-recap-calendar').count(),0);
await page.locator('.invoice-recap-table').getByRole('button',{name:'1/BB/X/2026',exact:true}).click();await page.getByRole('dialog',{name:'Detail invoice rekap'}).waitFor();assert.ok(await page.getByText('Dasar data harian',{exact:true}).isVisible());assert.ok(await page.getByText('PDF + Excel tersimpan di Drive',{exact:true}).isVisible());assert.ok((await page.getByRole('link',{name:'Dokumen Pendukung',exact:true}).getAttribute('href')).includes('document=1'));await page.getByRole('button',{name:'Preview PDF',exact:true}).click();await page.locator('iframe[title="Preview PDF invoice rekap"]').waitFor();await page.getByRole('button',{name:'Tutup detail',exact:true}).click();
await page.getByLabel('Filter kategori rekap').selectOption('Guru');assert.equal(await page.locator('.invoice-recap-table tbody tr').count(),1);await page.getByLabel('Filter kategori rekap').selectOption('');await page.getByLabel('Filter status rekap').selectOption('');assert.equal(await page.locator('.invoice-recap-table tbody tr').count(),3);assert.ok((await page.locator('.invoice-recap-table tfoot').innerText()).includes('Rp 100.300'));
await page.getByRole('button',{name:'Pilih minggu ini semua',exact:true}).click();await page.getByRole('checkbox',{name:'Pilih rekap 1/BB/X/2026 1'}).waitFor();await page.waitForFunction(()=>document.querySelector('[aria-label="Pilih rekap 1/BB/X/2026 1"]')?.checked);
await page.getByLabel('Rekap dari tanggal').fill('2026-09-28');await page.getByLabel('Rekap sampai tanggal').fill('2026-10-09');await page.locator('.invoice-recap-table tbody tr').first().waitFor();assert.equal(params.get('start_date'),'2026-09-28');assert.equal(params.get('end_date'),'2026-10-09');
for(const width of [360,768,904,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);}console.log('PASS weekly/range/category/status filters, split payment totals, selections, popup PDF/archive/supporting links and responsive widths');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});

