const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const React = require('react');
const { create, act } = require('react-test-renderer');
const esbuild = require('esbuild');
const root = path.resolve(__dirname, '..');
const output = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'lpdh-tabs-')), 'test.cjs');
const text = node => node.children.map(x => typeof x === 'string' ? x : text(x)).join('');

(async () => {
  await esbuild.build({ entryPoints: [path.join(root, 'src/lpdh/LpdhForms.jsx')], outfile: output, bundle: true, platform: 'node', format: 'cjs', plugins: [{ name: 'fixture', setup(build) {
    build.onResolve({ filter: /^react$/ }, () => ({ path: require.resolve('react'), external: true }));
    build.onResolve({ filter: /lpdhApi\.js$/ }, () => ({ path: 'api', namespace: 'fixture' }));
    build.onLoad({ filter: /.*/, namespace: 'fixture' }, () => ({ contents: 'export const arrayBufferToBase64=()=>"";export const downloadBase64=()=>{};', loader: 'js' }));
  } }] });
  const { MasterPanel, DailyPanel } = require(output);
  let masters = { identity:{ sppgName:'Identitas Tetap' }, schools:[{name:'Sekolah Awal',schoolType:'SD/MI',smallPortions:10,largePortions:20}], posyandu:[{name:'Pos Uji',balitaSmall:4,pregnantLarge:2}], volunteers:[{code:'R1',name:'Andi',role:'Masak',dailyRate:90000},{code:'R2',name:'Budi',role:'Supir',dailyRate:100000}],operations:[{name:'Gas LPG',category:'GAS',defaultPrice:100},{name:'Sabun',category:'Alat kebersihan',defaultPrice:200}] };
  const saved = [], api = { officialTemplateStatus:async()=>({installed:false}),saveMasters:async(site,data)=>saved.push(structuredClone(data)) };
  function MasterHarness({site='MAJA'}) { const [value,setValue]=React.useState(masters); return React.createElement(MasterPanel,{site,masters:value,setMasters:next=>{masters=next;setValue(next);},api}); }
  let view;
  await act(async()=>{view=create(React.createElement(MasterHarness));});
  const tab = name => view.root.findAllByProps({role:'tab'}).find(node=>text(node)===name);
  const button = name => view.root.findAllByType('button').find(node=>text(node).trim()===name);
  const switchTab = async name => { await act(async()=>tab(name).props.onClick()); assert.equal(view.root.findAllByProps({role:'tabpanel'}).length,1);assert.equal(tab(name).props['aria-selected'],true); };
  assert.equal(view.root.findAllByProps({role:'tab'}).length,10);
  assert.equal(tab('Sekolah').props['aria-selected'],true);
  assert.equal(view.root.findAllByType('input').some(node=>node.props.value==='Pos Uji'),false,'inactive sections are not rendered');
  await act(async()=>view.root.findByProps({'aria-label':'Porsi kecil sekolah 1'}).props.onChange({target:{value:'12'}}));
  await switchTab('Posyandu');
  await act(async()=>view.root.findAllByType('input').find(node=>node.props.value==='Pos Uji').props.onChange({target:{value:'Pos Diedit'}}));
  await switchTab('Sekolah');
  assert.equal(view.root.findByProps({'aria-label':'Porsi kecil sekolah 1'}).props.value,12,'unsaved school edits survive switching');
  await switchTab('Relawan');
  const query=()=>view.root.findByProps({type:'search'});
  await act(async()=>query().props.onChange({target:{value:'bUdI'}}));
  assert.equal(view.root.findAllByType('tbody')[0].findAllByType('tr').length,1);
  await act(async()=>view.root.findByProps({'aria-label':'Tarif/Hari · baris 2'}).props.onChange({target:{value:'123000'}}));
  assert.equal(masters.volunteers[0].dailyRate,90000);
  assert.equal(masters.volunteers[1].dailyRate,123000,'filtered edit uses original row index');
  await act(async()=>query().props.onChange({target:{value:'tidak ditemukan'}}));
  assert.ok(text(view.root).includes('Tidak ada hasil'));
  await act(async()=>button('Hapus pencarian').props.onClick());
  assert.equal(view.root.findAllByType('tbody')[0].findAllByType('tr').length,2);
  assert.equal(saved.length,0,'tabs and filters never save');
  await act(async()=>button('Simpan Semua Master').props.onClick());
  assert.equal(saved[0].schools[0].smallPortions,12);
  assert.equal(saved[0].posyandu[0].name,'Pos Diedit');
  assert.equal(saved[0].volunteers.length,2,'save includes all hidden categories and filtered rows');
  assert.equal(saved[0].identity.sppgName,'Identitas Tetap');
  let prevented=false;
  await act(async()=>tab('Relawan').props.onKeyDown({key:'End',preventDefault(){prevented=true;}}));
  assert.equal(prevented,true);assert.equal(tab('Parameter').props['aria-selected'],true);
  await act(async()=>view.update(React.createElement(MasterHarness,{site:'CEMPLANG'})));
  assert.equal(tab('Sekolah').props['aria-selected'],true,'site switch resets active tab');
  await act(async()=>view.unmount());

  let daily, savedDaily;
  const initial={pm:{rows:[{code:'KS-02',label:'SD Uji',portion:'Kecil',distributed:10,received:10}],production:{produced:15}},rawMaterials:[{name:'Beras',qty:2,price:100,sourceDocumentId:9,invoiceNo:'BB-UJI'}],volunteerPayments:[{name:'Andi',role:'Masak',workDays:1,dailyRate:90000,sourceDocumentId:10},{name:'Budi',role:'Supir',workDays:1,dailyRate:100000,sourceDocumentId:10}]};
  function DailyHarness({serviceDate='2026-10-05'}) { const [value,setValue]=React.useState(initial);daily=value;return React.createElement(DailyPanel,{site:'MAJA',serviceDate,masters,daily:value,setDaily:setValue,api:{saveDaily:async(site,date,data)=>{savedDaily=structuredClone(data);}}}); }
  await act(async()=>{view=create(React.createElement(DailyHarness));});
  assert.equal(view.root.findAllByProps({role:'tab'}).length,9);
  await act(async()=>view.root.findByProps({'aria-label':'Distribusi POP · baris 1'}).props.onChange({target:{value:'9'}}));
  await switchTab('D · Insentif Yayasan');
  const paid=view.root.findAllByType('label').find(node=>text(node)==='Nilai dibayar').findByType('input');
  await act(async()=>paid.props.onChange({target:{value:'12345'}}));
  await switchTab('C1 · Relawan');
  await act(async()=>query().props.onChange({target:{value:'Budi'}}));
  assert.equal(view.root.findAllByType('tbody')[0].findAllByType('tr').length,1);
  assert.equal(query().findAllByType('fieldset').length,0);
  assert.equal(view.root.findAllByType('fieldset')[0].props.disabled,true,'FINAL financial inputs remain locked');
  assert.equal(query().parent.type,'div','search is outside the disabled fieldset');
  await act(async()=>button('Simpan & Validasi').props.onClick());
  assert.equal(savedDaily.pm.rows[0].distributed,9);
  assert.equal(savedDaily.incentive.paidAmount,12345);
  assert.equal(savedDaily.volunteerPayments.length,2,'filtered save retains all FINAL recipients');
  assert.equal(savedDaily.rawMaterials[0].sourceDocumentId,9);
  await switchTab('A · Penerima Manfaat');
  assert.equal(view.root.findByProps({'aria-label':'Distribusi POP · baris 1'}).props.value,9);
  await act(async()=>view.update(React.createElement(DailyHarness,{serviceDate:'2026-10-06'})));
  assert.equal(tab('A · Penerima Manfaat').props['aria-selected'],true);
  assert.ok(view.root.findAllByType('td').every(node=>node.props['data-label']),'mobile cards have field labels');
  await act(async()=>view.unmount());
  console.log('PASS LPDH tabs/search: unsaved edits, source indexes, all-category saves, locked FINAL, keyboard navigation and context resets');
})().catch(error=>{console.error(error);process.exitCode=1;});
