const assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),esbuild=require('esbuild');
const{chromium}=require('playwright');
(async()=>{const root=path.resolve(__dirname,'..'),out=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'ops-recap-')),'fixture.js');
await esbuild.build({stdin:{contents:`import React from'react';import{createRoot}from'react-dom/client';import Recap from'./src/lpdh/InvoiceRecap.jsx';createRoot(document.getElementById('root')).render(<Recap site="MAJA"/>);`,resolveDir:root,loader:'jsx'},outfile:out,bundle:true,format:'iife',plugins:[{name:'offline',setup(b){b.onResolve({filter:/auth\/session.js$/},()=>({path:'session',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:'export const CORE_API="http://ops.test";export const readSessionToken=()=>"synthetic";',loader:'js'}));}}]});
const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();let requested,exported;
await page.route('**/*',r=>{const url=r.request().url();if(url.includes('operational-items.xlsx')){exported=new URL(url).searchParams;return r.fulfill({contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',body:Buffer.from('test workbook')});}if(url.includes('operational-items?')){requested=new URL(url).searchParams;return r.fulfill({contentType:'application/json',body:JSON.stringify({invoiceCount:2,itemCount:1,totalAmount:500,items:[{itemName:'APD',category:'APD',unit:'paket',quantity:5,amount:500,invoiceCount:2,dayCount:2}]})});}if(url.includes('/v1/'))return r.fulfill({contentType:'application/json',body:'{"documents":[]}'});return r.fulfill({contentType:'text/html',body:'<meta name="viewport" content="width=device-width,initial-scale=1"><div id="root"></div>'});});
await page.goto('http://ops.test');await page.addScriptTag({path:out});await page.addStyleTag({content:fs.readFileSync(path.join(root,'src/lpdh/lpdh.css'),'utf8')});await page.getByRole('button',{name:'Rekap Item Operasional',exact:true}).click();await page.getByRole('cell',{name:'paket',exact:true}).waitFor();assert.equal(requested.get('site'),'MAJA');assert.equal(new Date(requested.get('start_date')+'T12:00:00').getDay(),1);assert.equal(new Date(requested.get('end_date')+'T12:00:00').getDay(),5);assert.ok((await page.locator('tfoot').innerText()).includes('Rp 500'));
await page.getByLabel('Rekap dari tanggal').fill('2026-09-28');await page.getByLabel('Rekap sampai tanggal').fill('2026-10-09');await page.getByRole('cell',{name:'paket',exact:true}).waitFor();await page.getByRole('button',{name:'Unduh Excel Item Operasional',exact:true}).click();await page.waitForFunction(()=>document.querySelector('button.primary')?.textContent==='Unduh Excel Item Operasional');assert.equal(exported.get('start_date'),'2026-09-28');assert.equal(exported.get('end_date'),'2026-10-09');
for(const width of[360,904,1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`overflow ${width}`);}console.log('PASS item recap tab, Monday-Friday default, custom range, Excel request and responsive widths');}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});

