import React, { useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import { operationsApi } from "./apiClient";

const money=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
export default function OperationsAccountantBgn(){
  const [site,setSite]=useState(""); const [accountant,setAccountant]=useState([]); const [bgn,setBgn]=useState([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const load=async()=>{setLoading(true);setError("");try{const [a,b]=await Promise.all([operationsApi.getAccountantFlow(site),operationsApi.getBgnFlow(site)]);setAccountant(a?.items||[]);setBgn(b?.items||[]);}catch(e){setError(e.message||"Gagal mengambil alur akuntan/BGN");}finally{setLoading(false);}};
  useEffect(()=>{load();},[site]);
  return <div className="ops-domain-stack"><section className="ops-module"><div className="ops-module-header"><div><span className="ops-kicker">ACCOUNTANT</span><h3>Excel & Invoice Akuntan</h3><p>Maja → Tiara · Cemplang → Uya.</p></div><div className="ops-inline-controls"><select value={site} onChange={e=>setSite(e.target.value)}><option value="">Semua site</option><option value="MAJA">Maja</option><option value="CEMPLANG">Cemplang</option></select><button onClick={load} disabled={loading}><RefreshCw size={15}/> Refresh</button></div></div>{error&&<div className="ops-error">{error}</div>}<div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Site</th><th>Akuntan</th><th>Excel Sent</th><th>Status</th><th>Invoice</th><th>Nilai</th><th>Diterima</th></tr></thead><tbody>{accountant.map(x=><tr key={`${x.submission_id}-${x.invoice_id||0}`}><td>{x.site}</td><td>{x.accountant_code}</td><td>{x.sent_at||"-"}</td><td>{x.submission_status}</td><td>{x.invoice_number||"-"}</td><td>{money(x.invoice_amount)}</td><td>{x.received_at||"-"}</td></tr>)}{!loading&&accountant.length===0&&<tr><td colSpan="7" className="ops-empty-cell">Belum ada submission akuntan.</td></tr>}</tbody></table></div></section>
  <section className="ops-module"><div className="ops-module-header"><div><span className="ops-kicker">BGN</span><h3>Maker & Approval</h3><p>Maker, daftar approval, dan approval confirmed adalah state terpisah.</p></div></div><div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>Site</th><th>Maker</th><th>Referensi</th><th>Nilai</th><th>Maker Status</th><th>Approver</th><th>Approval</th><th>Approved</th></tr></thead><tbody>{bgn.map(x=><tr key={x.maker_id}><td>{x.site}</td><td>#{x.maker_id}</td><td>{x.reference_number||"-"}</td><td>{money(x.maker_amount)}</td><td>{x.maker_status}</td><td>{x.approver_code||"-"}</td><td>{x.approval_status||"Belum diminta"}</td><td>{x.approved_at||"-"}</td></tr>)}{!loading&&bgn.length===0&&<tr><td colSpan="8" className="ops-empty-cell">Belum ada maker BGN.</td></tr>}</tbody></table></div></section></div>;
}
