import React,{useEffect,useRef,useState} from 'react';
import {CORE_API,readSessionToken} from '../auth/session.js';
import {DELIVERY_KINDS,deliveryHtml} from './deliveryPrint.mjs';
import './delivery.css';
import './delivery-preview.css';
async function api(path,options={}){
  const r=await fetch(`${CORE_API}/v1/accountant-documents${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${readSessionToken()}`}});
  const body=await r.json();if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:'Dokumen gagal diproses');return body;
}
export default function DeliveryWorkspace({role}){
  const params=new URLSearchParams(window.location.search);
  const [site,setSite]=useState(role==='OWNER'?(params.get('site')==='CEMPLANG'?'CEMPLANG':'MAJA'):role);
  const [month,setMonth]=useState((params.get('date')||new Date().toLocaleDateString('en-CA')).slice(0,7));
  const [packages,setPackages]=useState([]),[selected,setSelected]=useState(null),[mode,setMode]=useState('calendar'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const version=useRef(0);
  const [profiles,setProfiles]=useState({}),[profileDraft,setProfileDraft]=useState({}),[editKind,setEditKind]=useState('SJ'),[checked,setChecked]=useState([]),[bulkKinds,setBulkKinds]=useState(['SJ']),[anchorKind,setAnchorKind]=useState('SJ'),[anchorPeriod,setAnchorPeriod]=useState(''),[anchorNumber,setAnchorNumber]=useState(1);
  const activeSettings=profileDraft[editKind]||profiles[editKind]||selected?.settings||{};
  const printPackage=p=>({...p,settings:{...p.settings,byKind:{...p.settings?.byKind,...profiles,...profileDraft}}});
  function changeMaster(key,value){setProfileDraft(old=>({...old,[editKind]:{...activeSettings,[key]:value}}));}
  const [previewOpen,setPreviewOpen]=useState(false),[previewKind,setPreviewKind]=useState('SJ');
  const previewFrame=useRef(null),editor=useRef(null);
  useEffect(()=>{editor.current=document.querySelector('.delivery-master-editor');},[selected]);
  async function load(){const v=++version.current;setBusy(true);setError('');try{const r=await api(`/delivery-sync?${new URLSearchParams({site,month})}`,{method:'POST'});if(v===version.current){setPackages(r.packages||[]);setSelected(null);}}catch(e){if(v===version.current)setError(e.message);}finally{if(v===version.current)setBusy(false);}}
  useEffect(()=>{setPreviewOpen(false);load();return()=>{version.current++};},[site,month]);
  useEffect(()=>{if(!previewOpen)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const close=e=>{if(e.key==='Escape')setPreviewOpen(false);};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=overflow;window.removeEventListener('keydown',close);};},[previewOpen]);
  useEffect(()=>{const receive=e=>{if(e.origin!==window.location.origin||e.data?.type!=='delivery-positions'||e.data.documentId!==selected?.document.id||!DELIVERY_KINDS[e.data.kind])return;const kind=e.data.kind;setProfileDraft(old=>({...old,[kind]:{...(old[kind]||profiles[kind]||selected.settings||{}),positions:e.data.positions}}));};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[selected,profiles]);
  const visible=packages.filter(p=>`${p.document.documentNumber} ${p.document.serviceDate}`.toLowerCase().includes(query.toLowerCase()));
  function field(key,label){return <label>{label}<input value={activeSettings[key]||''} onChange={e=>changeMaster(key,e.target.value)}/></label>;}
  useEffect(()=>{let cancelled=false;setProfiles({});setProfileDraft({});setChecked([]);api(`/delivery-controls?site=${site}`).then(r=>{if(!cancelled)setProfiles(r.profiles||{});}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;};},[site]);
  useEffect(()=>{setChecked([]);},[month]);
  async function saveMaster(){const v=version.current,kind=editKind,settings=activeSettings;setBusy(true);setError('');try{await api(`/delivery-profiles/${kind}?site=${site}`,{method:'PUT',body:JSON.stringify({settings})});if(v===version.current)setProfiles(old=>({...old,[kind]:settings}));}catch(e){if(v===version.current)setError(e.message);}finally{if(v===version.current)setBusy(false);}}
  async function saveAnchor(){setBusy(true);setError('');try{await api(`/delivery-anchors/${anchorKind}?site=${site}`,{method:'PUT',body:JSON.stringify({period:anchorPeriod,next_number:Number(anchorNumber)})});window.alert('Jangkar disimpan untuk paket baru. Nomor paket yang sudah ada tetap.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  async function bulkPrint(){const targets=packages.filter(p=>checked.includes(p.document.id)&&p.document.status==='FINAL');if(!targets.length||!bulkKinds.length)return;const w=window.open('','_blank');if(!w){setError('Izinkan pop-up untuk cetak.');return;}try{const pages=[];for(const p of targets){const current=await api(`/${p.document.id}`);if(current.document.status!=='FINAL')throw new Error('Salah satu invoice sudah dibatalkan. Refresh daftar.');for(const kind of bulkKinds){const doc=new DOMParser().parseFromString(deliveryHtml(printPackage({...p,document:current.document}),kind),'text/html');pages.push(doc.querySelector('.paper').outerHTML);if(!w.document.getElementById('bulk-style')){w.document.write('<!doctype html><html><head><title>Cetak dokumen terpilih</title><style id="bulk-style">'+doc.querySelector('style').textContent+' .paper{break-after:page}.paper:last-child{break-after:auto}</style></head><body><div class="toolbar"><button onclick="window.print()">Cetak / Simpan PDF</button></div>');}}}w.document.write(pages.join('')+'</body></html>');w.document.close();}catch(e){w.close();setError(e.message);}}
  async function upload(key,file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>5*1024*1024){setError('Gunakan PNG/JPG/WebP maksimal 5 MB per file.');return;}const reader=new FileReader();const kind=editKind,base=activeSettings;reader.onload=()=>setProfileDraft(old=>({...old,[kind]:{...base,[key]:reader.result}}));reader.readAsDataURL(file);}
  async function save(){const v=version.current,target=selected;setBusy(true);setError('');try{await api(`/${target.document.id}/delivery-settings`,{method:'PUT',body:JSON.stringify({settings:target.settings||{}})});if(v===version.current)setPackages(rows=>rows.map(p=>p.document.id===target.document.id?target:p));}catch(e){if(v===version.current)setError(e.message);}finally{if(v===version.current)setBusy(false);}}
  async function print(kind){if(selected.document.status!=='FINAL')return;const target=selected,w=window.open('','_blank');if(!w){setError('Izinkan pop-up untuk membuka cetak.');return;}try{const current=await api(`/${target.document.id}`);if(current.document.status!=='FINAL')throw new Error('Invoice sudah dibatalkan. Refresh daftar; cetak aktif dihentikan.');w.document.open();w.document.write(deliveryHtml(printPackage({...target,document:current.document}),kind));w.document.close();}catch(e){w.close();setError(e.message);}}
  async function printPreview(){const id=selected.document.id;setError('');try{const current=await api(`/${id}`);if(current.document.status!=='FINAL')throw new Error('Invoice sudah dibatalkan. Refresh daftar; cetak dihentikan.');if(previewFrame.current?.dataset.documentId!==String(id))return;previewFrame.current.contentWindow.focus();previewFrame.current.contentWindow.print();}catch(e){setError(e.message);}}
  const card=p=><div key={p.document.id}><label><input type="checkbox" aria-label={`Pilih ${p.document.documentNumber}`} disabled={p.document.status!=='FINAL'} checked={checked.includes(p.document.id)} onChange={e=>setChecked(old=>e.target.checked?[...old,p.document.id]:old.filter(id=>id!==p.document.id))}/> Pilih cetak</label><button className="delivery-card" key={p.document.id} onClick={()=>{setSelected(p);setPreviewKind('SJ');setPreviewOpen(p.document.status==='FINAL');}}><strong>{p.document.documentNumber}</strong><span>{p.document.documentType==='BAHAN_BAKU'?'Bahan baku':'Operasional'} · {p.document.serviceDate}</span><span>{p.document.items.length} barang · {Number(p.document.total).toLocaleString('id-ID',{style:'currency',currency:'IDR'})}</span><b>{p.document.status==='FINAL'?'Klik untuk preview & cetak':'DIBATALKAN · Riwayat'}</b></button></div>;
  const start=new Date(month+'-01T12:00:00'),days=new Date(start.getFullYear(),start.getMonth()+1,0).getDate();
  return <main className="delivery-workspace"><header><h1>Dokumen Pendamping · {site}</h1><a href={`/lpdh?site=${site}`}>Kembali ke LPDH</a></header><p>Otomatis dari invoice bahan baku dan operasional FINAL. PO H−2; surat jalan/ceklis H−1; kuitansi H+1 dari HPE. Paket ini bukan transaksi keuangan baru.</p><div className="delivery-controls">{role==='OWNER'&&<select aria-label="Dapur" value={site} onChange={e=>setSite(e.target.value)}><option>MAJA</option><option>CEMPLANG</option></select>}<input aria-label="Bulan" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button disabled={busy} onClick={load}>Refresh</button><button onClick={()=>setMode('calendar')}>Kalender</button><button onClick={()=>setMode('list')}>Daftar</button><input aria-label="Cari invoice" placeholder="Cari nomor invoice / tanggal" value={query} onChange={e=>setQuery(e.target.value)}/></div>{error&&<p role="alert" className="delivery-error">{error}</p>}{busy&&<p>Memuat / menyimpan…</p>}
    {mode==='list'?<div className="delivery-list">{visible.map(card)}</div>:<div className="delivery-calendar">{['Min','Sen','Sel','Rab','Kam','Jum','Sab'].map(x=><b key={x}>{x}</b>)}{Array.from({length:start.getDay()},(_,i)=><div key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0');return <div key={date}><b>{i+1}</b>{visible.filter(p=>p.document.serviceDate===date).map(card)}</div>;})}</div>}
    <section className="delivery-editor"><h2>Cetak sekaligus · {checked.length} kartu dipilih</h2><div className="delivery-controls">{Object.entries(DELIVERY_KINDS).map(([kind,label])=><label key={kind}><input type="checkbox" checked={bulkKinds.includes(kind)} onChange={e=>setBulkKinds(old=>e.target.checked?[...old,kind]:old.filter(k=>k!==kind))}/>{label}</label>)}<button disabled={busy||!checked.length||!bulkKinds.length} onClick={bulkPrint}>Preview &amp; cetak terpilih</button><button onClick={()=>setChecked(visible.filter(p=>p.document.status==='FINAL').map(p=>p.document.id))}>Pilih semua yang tampil</button><button onClick={()=>setChecked([])}>Hapus pilihan</button></div></section>
    <details className="delivery-editor"><summary>Jangkar nomor Dokumen Pendamping</summary><p>Berlaku untuk paket baru saja. Kuitansi memakai periode tahun; PO, surat jalan, dan ceklis memakai tahun-bulan sesuai tanggal surat. Nomor yang sudah dialokasikan tidak boleh diulang.</p><div className="delivery-controls"><select aria-label="Jenis jangkar" value={anchorKind} onChange={e=>{setAnchorKind(e.target.value);setAnchorPeriod('');}}>{Object.entries(DELIVERY_KINDS).map(([kind,label])=><option value={kind} key={kind}>{label}</option>)}</select><input aria-label="Periode jangkar" type={anchorKind==='KUI'?'number':'month'} placeholder="2026" value={anchorPeriod} onChange={e=>setAnchorPeriod(e.target.value)}/><input aria-label="Nomor berikutnya" type="number" min="1" value={anchorNumber} onChange={e=>setAnchorNumber(e.target.value)}/><button disabled={busy||!anchorPeriod} onClick={saveAnchor}>Simpan jangkar nomor berikutnya</button></div></details>
    {!busy&&!visible.length&&<p>Belum ada invoice bahan baku/operasional FINAL pada bulan ini.</p>}
    {selected&&<section className="delivery-editor delivery-master-editor"><h2>{selected.document.documentNumber}</h2><p>HPE {selected.document.serviceDate}. Nomor paket disimpan di server dan tidak berubah saat Refresh.</p><div className="delivery-controls">{Object.entries(DELIVERY_KINDS).map(([kind,label])=><button key={kind} disabled={selected.document.status!=='FINAL'} onClick={()=>print(kind)}>{label} · {selected.dates[kind]} · {selected.numbers[kind]}</button>)}</div>{selected.document.status!=='FINAL'?<p className="delivery-error">Invoice dibatalkan. Paket tetap menjadi riwayat; cetak aktif dinonaktifkan.</p>:<><h3>Master Dokumen Pendamping · {DELIVERY_KINDS[editKind]}</h3><div className="delivery-controls">{Object.entries(DELIVERY_KINDS).map(([kind,label])=><button key={kind} onClick={()=>setEditKind(kind)} aria-pressed={editKind===kind}>{label}</button>)}</div><p>Master terpisah per jenis surat dan dapur; tidak mengubah master LPDH.</p><div className="delivery-fields">{field('foundation','Nama yayasan / kop BGN')}{field('kitchen','Nama SPPG')}{field('address','Alamat kop SPPG')}{field('sender','Pengirim / kop surat jalan')}{field('senderAddress','Alamat pengirim')}{field('receiver','Penerima')}{field('receiverAddress','Alamat penerima')}{field('signatory','Penandatangan pengirim / penerima uang')}{field('supervisor','Staf Pengawas Keuangan')}{field('receiverSignatory','Nama penerima barang / gudang')}{field('driver','Supir / kurir')}{field('security','Security / penanggung jawab')}{field('orderer','Pemesan PO')}{field('moneyFrom','Sudah terima dari')}{field('paymentFor','Untuk pembayaran')}{[['logo','Logo kop'],['signature','Tanda tangan'],['stamp','Stempel']].map(([key,label])=><label key={key}>{label}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(key,e.target.files[0])}/>{activeSettings[key]&&<><img alt={label} src={activeSettings[key]}/><button onClick={()=>changeMaster(key,'')}>Hapus aset</button></>}</label>)}</div><label><input type="checkbox" checked={activeSettings.showDetails!==false} onChange={e=>changeMaster('showDetails',e.target.checked)}/> Tampilkan rincian pada kuitansi</label><p>Di jendela cetak, teks bisa diedit dan stempel/TTD bisa digeser atau diubah ukurannya. Koreksi di jendela cetak hanya berlaku untuk cetakan itu.</p><button disabled={busy} onClick={saveMaster}>Simpan master jenis surat</button></>}</section>}
    {previewOpen&&selected&&<div className="delivery-preview-overlay"><section role="dialog" aria-modal="true" aria-label="Preview Dokumen Pendamping" className="delivery-preview-dialog"><header><strong>{selected.document.documentNumber} · {DELIVERY_KINDS[previewKind]}</strong><button autoFocus onClick={()=>setPreviewOpen(false)}>Tutup preview</button></header><div className="delivery-controls" role="tablist" aria-label="Jenis dokumen">{Object.entries(DELIVERY_KINDS).map(([kind,label])=><button role="tab" aria-selected={previewKind===kind} key={kind} onClick={()=>setPreviewKind(kind)}>{label}</button>)}<button className="delivery-print-primary" onClick={printPreview}>Cetak / Simpan PDF</button><button onClick={()=>{setPreviewOpen(false);setTimeout(()=>editor.current?.scrollIntoView({behavior:'smooth'}),0);}}>Edit identitas &amp; aset</button></div><p>Nomor {selected.numbers[previewKind]} · {selected.dates[previewKind]}. Klik teks untuk koreksi cetak; gambar dapat digeser dan diubah ukurannya.</p>{error&&<p role="alert" className="delivery-error">{error}</p>}<iframe ref={previewFrame} data-document-id={selected.document.id} title="Preview cetak editable" srcDoc={deliveryHtml(printPackage(selected),previewKind)} onLoad={e=>{const doc=e.currentTarget.contentDocument;doc.querySelector('.toolbar').style.display='none';const style=doc.createElement('style');style.textContent='@media screen{.paper{margin:8px auto;zoom:'+Math.min(1,(e.currentTarget.clientWidth-16)/794)+'}}@media print{.paper{zoom:1!important}}';doc.head.appendChild(style);}}/></section></div>}
  </main>;
}
