import React,{useEffect,useRef,useState} from 'react';
import {CORE_API,readSessionToken} from '../auth/session.js';
import {DELIVERY_KINDS,deliveryHtml} from './deliveryPrint.mjs';
import './delivery.css';
import './delivery-preview.css';
async function api(path,options={}){
  const r=await fetch(`${CORE_API}/v1/accountant-documents${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${readSessionToken()}`}});
  const body=await r.json();if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:'Dokumen gagal diproses');return body;
}
export default function DeliveryWorkspace({role}){
  const params=new URLSearchParams(window.location.search);
  const [site,setSite]=useState(role==='OWNER'?(params.get('site')==='CEMPLANG'?'CEMPLANG':'MAJA'):role);
  const [month,setMonth]=useState((params.get('date')||new Date().toLocaleDateString('en-CA')).slice(0,7));
  const [packages,setPackages]=useState([]),[selected,setSelected]=useState(null),[mode,setMode]=useState('calendar'),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const version=useRef(0);
  const [previewOpen,setPreviewOpen]=useState(false),[previewKind,setPreviewKind]=useState('SJ');
  const previewFrame=useRef(null),editor=useRef(null);
  useEffect(()=>{editor.current=document.querySelector('.delivery-editor');},[selected]);
  async function load(){const v=++version.current;setBusy(true);setError('');try{const r=await api(`/delivery-sync?${new URLSearchParams({site,month})}`,{method:'POST'});if(v===version.current){setPackages(r.packages||[]);setSelected(null);}}catch(e){if(v===version.current)setError(e.message);}finally{if(v===version.current)setBusy(false);}}
  useEffect(()=>{setPreviewOpen(false);load();return()=>{version.current++};},[site,month]);
  useEffect(()=>{if(!previewOpen)return;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';const close=e=>{if(e.key==='Escape')setPreviewOpen(false);};window.addEventListener('keydown',close);return()=>{document.body.style.overflow=overflow;window.removeEventListener('keydown',close);};},[previewOpen]);
  useEffect(()=>{const receive=e=>{if(e.origin!==window.location.origin||e.data?.type!=='delivery-positions')return;setSelected(p=>p?.document.id===e.data.documentId?{...p,settings:{...p.settings,positions:e.data.positions}}:p);};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[]);
  const visible=packages.filter(p=>`${p.document.documentNumber} ${p.document.serviceDate}`.toLowerCase().includes(query.toLowerCase()));
  function field(key,label){return <label>{label}<input value={selected.settings?.[key]||''} onChange={e=>setSelected({...selected,settings:{...selected.settings,[key]:e.target.value}})}/></label>;}
  async function upload(key,file){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1000000){setError('Gunakan PNG/JPG/WebP maksimal 1 MB.');return;}const reader=new FileReader();const target=selected.document.id;reader.onload=()=>setSelected(p=>p?.document.id===target?{...p,settings:{...p.settings,[key]:reader.result}}:p);reader.readAsDataURL(file);}
  async function save(){const v=version.current,target=selected;setBusy(true);setError('');try{await api(`/${target.document.id}/delivery-settings`,{method:'PUT',body:JSON.stringify({settings:target.settings||{}})});if(v===version.current)setPackages(rows=>rows.map(p=>p.document.id===target.document.id?target:p));}catch(e){if(v===version.current)setError(e.message);}finally{if(v===version.current)setBusy(false);}}
  async function print(kind){if(selected.document.status!=='FINAL')return;const target=selected,w=window.open('','_blank');if(!w){setError('Izinkan pop-up untuk membuka cetak.');return;}try{const current=await api(`/${target.document.id}`);if(current.document.status!=='FINAL')throw new Error('Invoice sudah dibatalkan. Refresh daftar; cetak aktif dihentikan.');w.document.open();w.document.write(deliveryHtml({...target,document:current.document},kind));w.document.close();}catch(e){w.close();setError(e.message);}}
  async function printPreview(){const id=selected.document.id;setError('');try{const current=await api(`/${id}`);if(current.document.status!=='FINAL')throw new Error('Invoice sudah dibatalkan. Refresh daftar; cetak dihentikan.');if(previewFrame.current?.dataset.documentId!==String(id))return;previewFrame.current.contentWindow.focus();previewFrame.current.contentWindow.print();}catch(e){setError(e.message);}}
  const card=p=><button className="delivery-card" key={p.document.id} onClick={()=>{setSelected(p);setPreviewKind('SJ');setPreviewOpen(p.document.status==='FINAL');}}><strong>{p.document.documentNumber}</strong><span>{p.document.documentType==='BAHAN_BAKU'?'Bahan baku':'Operasional'} · {p.document.serviceDate}</span><span>{p.document.items.length} barang · {Number(p.document.total).toLocaleString('id-ID',{style:'currency',currency:'IDR'})}</span><b>{p.document.status==='FINAL'?'Klik untuk preview & cetak':'DIBATALKAN · Riwayat'}</b></button>;
  const start=new Date(month+'-01T12:00:00'),days=new Date(start.getFullYear(),start.getMonth()+1,0).getDate();
  return <main className="delivery-workspace"><header><h1>Dokumen Pendamping · {site}</h1><a href={`/lpdh?site=${site}`}>Kembali ke LPDH</a></header><p>Otomatis dari invoice bahan baku dan operasional FINAL. PO H−2; surat jalan/ceklis H−1; kuitansi H+1 dari HPE. Paket ini bukan transaksi keuangan baru.</p><div className="delivery-controls">{role==='OWNER'&&<select aria-label="Dapur" value={site} onChange={e=>setSite(e.target.value)}><option>MAJA</option><option>CEMPLANG</option></select>}<input aria-label="Bulan" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><button disabled={busy} onClick={load}>Refresh</button><button onClick={()=>setMode('calendar')}>Kalender</button><button onClick={()=>setMode('list')}>Daftar</button><input aria-label="Cari invoice" placeholder="Cari nomor invoice / tanggal" value={query} onChange={e=>setQuery(e.target.value)}/></div>{error&&<p role="alert" className="delivery-error">{error}</p>}{busy&&<p>Memuat / menyimpan…</p>}
    {mode==='list'?<div className="delivery-list">{visible.map(card)}</div>:<div className="delivery-calendar">{['Min','Sen','Sel','Rab','Kam','Jum','Sab'].map(x=><b key={x}>{x}</b>)}{Array.from({length:start.getDay()},(_,i)=><div key={'blank'+i}/>)}{Array.from({length:days},(_,i)=>{const date=month+'-'+String(i+1).padStart(2,'0');return <div key={date}><b>{i+1}</b>{visible.filter(p=>p.document.serviceDate===date).map(card)}</div>;})}</div>}
    {!busy&&!visible.length&&<p>Belum ada invoice bahan baku/operasional FINAL pada bulan ini.</p>}
    {selected&&<section className="delivery-editor"><h2>{selected.document.documentNumber}</h2><p>HPE {selected.document.serviceDate}. Nomor paket disimpan di server dan tidak berubah saat Refresh.</p><div className="delivery-controls">{Object.entries(DELIVERY_KINDS).map(([kind,label])=><button key={kind} disabled={selected.document.status!=='FINAL'} onClick={()=>print(kind)}>{label} · {selected.dates[kind]} · {selected.numbers[kind]}</button>)}</div>{selected.document.status!=='FINAL'?<p className="delivery-error">Invoice dibatalkan. Paket tetap menjadi riwayat; cetak aktif dinonaktifkan.</p>:<><h3>Identitas &amp; aset cetak (invoice FINAL tidak berubah)</h3><div className="delivery-fields">{field('foundation','Nama yayasan / kop BGN')}{field('kitchen','Nama SPPG')}{field('address','Alamat kop SPPG')}{field('sender','Pengirim / kop surat jalan')}{field('senderAddress','Alamat pengirim')}{field('receiver','Penerima')}{field('receiverAddress','Alamat penerima')}{field('signatory','Penandatangan pengirim / penerima uang')}{field('supervisor','Staf Pengawas Keuangan')}{field('receiverSignatory','Nama penerima barang / gudang')}{field('driver','Supir / kurir')}{field('security','Security / penanggung jawab')}{field('orderer','Pemesan PO')}{field('moneyFrom','Sudah terima dari')}{field('paymentFor','Untuk pembayaran')}{[['logo','Logo kop'],['signature','Tanda tangan'],['stamp','Stempel']].map(([key,label])=><label key={key}>{label}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>upload(key,e.target.files[0])}/>{selected.settings?.[key]&&<><img alt={label} src={selected.settings[key]}/><button onClick={()=>setSelected({...selected,settings:{...selected.settings,[key]:''}})}>Hapus aset</button></>}</label>)}</div><label><input type="checkbox" checked={selected.settings?.showDetails!==false} onChange={e=>setSelected({...selected,settings:{...selected.settings,showDetails:e.target.checked}})}/> Tampilkan rincian pada kuitansi</label><p>Di jendela cetak, teks bisa diedit dan stempel/TTD bisa digeser atau diubah ukurannya. Koreksi di jendela cetak hanya berlaku untuk cetakan itu.</p><button disabled={busy} onClick={save}>Simpan identitas &amp; aset paket ini</button></>}</section>}
    {previewOpen&&selected&&<div className="delivery-preview-overlay"><section role="dialog" aria-modal="true" aria-label="Preview Dokumen Pendamping" className="delivery-preview-dialog"><header><strong>{selected.document.documentNumber} · {DELIVERY_KINDS[previewKind]}</strong><button autoFocus onClick={()=>setPreviewOpen(false)}>Tutup preview</button></header><div className="delivery-controls" role="tablist" aria-label="Jenis dokumen">{Object.entries(DELIVERY_KINDS).map(([kind,label])=><button role="tab" aria-selected={previewKind===kind} key={kind} onClick={()=>setPreviewKind(kind)}>{label}</button>)}<button className="delivery-print-primary" onClick={printPreview}>Cetak / Simpan PDF</button><button onClick={()=>{setPreviewOpen(false);setTimeout(()=>editor.current?.scrollIntoView({behavior:'smooth'}),0);}}>Edit identitas &amp; aset</button></div><p>Nomor {selected.numbers[previewKind]} · {selected.dates[previewKind]}. Klik teks untuk koreksi cetak; gambar dapat digeser dan diubah ukurannya.</p>{error&&<p role="alert" className="delivery-error">{error}</p>}<iframe ref={previewFrame} data-document-id={selected.document.id} title="Preview cetak editable" srcDoc={deliveryHtml(selected,previewKind)} onLoad={e=>{const doc=e.currentTarget.contentDocument;doc.querySelector('.toolbar').style.display='none';const style=doc.createElement('style');style.textContent='@media screen{.paper{margin:8px auto;zoom:'+Math.min(1,(e.currentTarget.clientWidth-16)/794)+'}}@media print{.paper{zoom:1!important}}';doc.head.appendChild(style);}}/></section></div>}
  </main>;
}
