export const DELIVERY_KINDS={PO:'Nota Pesanan',SJ:'Surat Jalan',CKL:'Ceklis Barang',KUI:'Kuitansi'};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const rp=value=>'Rp '+Number(value||0).toLocaleString('id-ID');
export function terbilang(n){
  n=Math.floor(Number(n)||0);const words=['','satu','dua','tiga','empat','lima','enam','tujuh','delapan','sembilan','sepuluh','sebelas'];
  if(n<0)return 'minus '+terbilang(-n);if(n<12)return words[n];if(n<20)return terbilang(n-10)+' belas';if(n<100)return terbilang(Math.floor(n/10))+' puluh '+terbilang(n%10);
  if(n<200)return 'seratus '+terbilang(n-100);if(n<1000)return terbilang(Math.floor(n/100))+' ratus '+terbilang(n%100);if(n<2000)return 'seribu '+terbilang(n-1000);
  for(const [v,w] of [[1e12,'triliun'],[1e9,'miliar'],[1e6,'juta'],[1000,'ribu']])if(n>=v)return (terbilang(Math.floor(n/v))+' '+w+' '+terbilang(n%v)).trim();return '';
}
export const DELIVERY_CSS=`
*{box-sizing:border-box}body{margin:0;background:#eee;color:#000;font:13px Arial,Helvetica,sans-serif}.paper{background:white;width:210mm;min-height:297mm;padding:20mm;margin:20px auto}.toolbar{position:sticky;top:0;background:#153e35;color:white;padding:12px;z-index:1000;display:flex;gap:10px;flex-wrap:wrap}.toolbar button{padding:8px;cursor:pointer}header{position:relative;text-align:center;border-bottom:4px double black;padding-bottom:16px;margin-bottom:28px}h1{font-size:18px;line-height:1.3;margin:0}h2{font-size:14px;margin:8px 0;text-transform:uppercase}header p{font-size:10px;font-style:italic;margin:8px 0;white-space:pre-line}.title{text-align:center;margin:24px 0;font-size:20px;text-decoration:underline}.meta{display:flex;justify-content:space-between;gap:24px;margin:20px 0}.meta>div{flex:1;white-space:pre-line}table{border-collapse:collapse;width:100%;margin:20px 0}th,td{border:1px solid black;padding:8px;vertical-align:top}th{background:#eee}tr{break-inside:avoid}thead{display:table-header-group}.signers{display:flex;justify-content:space-between;gap:20px;break-inside:avoid;margin-top:40px}.signer{text-align:center;flex:1;min-width:0}.sign-space{height:100px;position:relative}.asset{position:absolute;left:10px;top:0;width:100px;height:90px;resize:both;overflow:hidden;touch-action:none;cursor:move;z-index:2;border:1px dashed #888}.asset img{width:100%;height:100%;object-fit:contain;pointer-events:none}.asset.stamp{left:0;top:10px;width:100px;height:100px;opacity:.8;mix-blend-mode:multiply;transform:rotate(-5deg)}.asset.logo{top:0;left:0;width:80px;height:80px}.name{font-weight:bold;text-decoration:underline}.kui td{border:0;border-bottom:1px dotted #999;padding:12px}.kui td:first-child{font-weight:bold;font-style:italic;width:180px}.spell{background:#eee;border:1px solid #999;padding:12px;font-style:italic}.standard{font-family:'Times New Roman',serif}.standard header{text-align:left;border-bottom:3px double black}.standard header h1{white-space:pre-line;font-size:24px;padding-left:90px}.standard header p{padding-left:90px;font:14px 'Times New Roman',serif}.box{border:1px solid black;width:14px;height:14px;display:inline-block;margin-right:6px}.print-note{font-size:10px;color:#555}
@media print{@page{size:A4;margin:15mm}body{background:white}.toolbar{display:none}.paper{width:auto;min-height:0;padding:0;margin:0;box-shadow:none}.asset{border:0;resize:none}header{break-inside:avoid}.print-note{display:none}}`;
function image(settings,key,cls=''){
  const src=settings[key];if(!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(src||''))return '';
  const cfg=settings.positions?.[key]||{};
  const styles=[['x','left'],['y','top'],['w','width'],['h','height']].filter(([k])=>Number.isFinite(Number(cfg[k]))&&cfg[k]!==undefined).map(([k,css])=>`${css}:${Math.max(k==='w'||k==='h'?20:-500,Math.min(1200,Number(cfg[k])))}px`).join(';');
  return `<div class="asset ${cls}" data-asset="${key}" style="${styles}" contenteditable="false"><img src="${esc(src)}" alt="${esc(key)}"></div>`;
}
function signer(label,name,settings,withAssets=false){return `<div class="signer"><p>${esc(label)}</p><div class="sign-space">${withAssets?image(settings,'stamp','stamp')+image(settings,'signature'):''}</div><div class="name">${esc(name)||'........................................'}</div></div>`;}
export function deliveryHtml(pkg,kind){
  const doc=pkg.document,s=pkg.settings||{},h=doc.header||{},maja=doc.site==='MAJA';
  const foundation=s.foundation||(maja?'YAYASAN DERMAWAN MENTARI MEGHA':'YAYASAN MITRA MUKTI DERMAWAN');
  const kitchen=s.kitchen||(maja?'SPPG LEBAK MAJA SANGIANG 2, PROVINSI BANTEN':'SPPG CEMPLANG 2, JAWILAN, SERANG BANTEN');
  const address=s.address||(maja?'Jl. Kopi Sangiang, No. 46, RT.01 RW. 04, Desa Sangiang, Kecamatan Maja\nKabupaten Lebak, Provinsi Banten':'Jl. Cikande - Rangkasbitung Km.15. No 33, Desa Cemplang, Kec. Jawilan\nKabupaten Serang, Provinsi Banten');
  const dt=new Date(pkg.dates[kind]+'T12:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});
  const kop=kind==='SJ'?`<header>${image(s,'logo','logo')}<h1>${esc(s.sender||h.issuerName)}</h1><p>${esc(s.senderAddress||h.issuerAddress)}</p></header>`:`<header>${image(s,'logo','logo')}<h1>BADAN GIZI NASIONAL<br>REPUBLIK INDONESIA</h1><h2>${esc(foundation)}<br>${esc(kitchen)}</h2><p>${esc(address)}</p></header>`;
  const name=s.receiver||h.recipientName||kitchen;
  const details=doc.items.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.itemName)}</td><td>${esc(x.quantity)}</td><td>${esc(x.unit)}</td>${kind==='CKL'?'<td></td><td><span class="box"></span>Baik<br><br><span class="box"></span>Rusak</td>':kind==='KUI'?`<td>${rp(x.unitPrice)}</td><td>${rp(x.lineTotal)}</td>`:''}<td>${esc(x.metadata?.note||'')}</td></tr>`).join('');
  let body='';
  if(kind==='KUI'){
    body=`<h3 class="title">K U I T A N S I</h3><p style="text-align:center"><b>No. ${esc(pkg.numbers.KUI)}</b></p><table class="kui"><tr><td>Sudah terima dari</td><td>${esc(s.moneyFrom||`Staf Pengawas Keuangan ${kitchen} (${foundation})`)}</td></tr><tr><td>Banyaknya uang</td><td><b>${rp(doc.total)}</b></td></tr><tr><td>Terbilang</td><td><div class="spell">${esc(terbilang(doc.total))} rupiah</div></td></tr><tr><td>Untuk pembayaran</td><td>${esc(s.paymentFor||`Pembayaran ${doc.documentType==='BAHAN_BAKU'?'Bahan Baku':'Operasional lainnya'} dari Koperasi, invoice ${doc.documentNumber}, HPE ${doc.serviceDate}`)}</td></tr></table>${s.showDetails===false?'':`<p><b>Rincian Pembayaran:</b></p><table><thead><tr><th>No</th><th>Uraian</th><th>Vol</th><th>Satuan</th><th>Harga Satuan</th><th>Jumlah Total</th><th>Keterangan</th></tr></thead><tbody>${details}<tr><td colspan="5"><b>Total Dibayar</b></td><td colspan="2"><b>${rp(doc.total)}</b></td></tr></tbody></table>`}<p style="text-align:right">${maja?'Lebak':'Serang'}, ${dt}</p><div class="signers">${signer('Lunas Dibayar, Staf Pengawas Keuangan',s.supervisor,{},false)}${signer('Yang Menerima,',s.signatory||h.senderSignatory,s,true)}</div>`;
  }else{
    const title=kind==='PO'?'NOTA PESANAN BAHAN MAKANAN':kind==='SJ'?'SURAT JALAN':'CEKLIS PENERIMAAN BARANG';
    body=`<h3 class="title">${title}</h3><p><b>No. ${esc(pkg.numbers[kind])}</b> · ${dt}</p><div class="meta"><div>${kind==='PO'?'Dari':'Penerima'}: <b>${esc(name)}</b><br>Alamat: ${esc(s.receiverAddress||h.recipientAddress||address)}</div><div>${kind==='PO'?'Kepada: '+esc(s.sender||h.issuerName):'Nama Supir: '+esc(s.driver||'........................................')}<br>Invoice acuan: ${esc(doc.documentNumber)}${kind==='CKL'?'<br>No. Surat Jalan: '+esc(pkg.numbers.SJ):''}</div></div><table><thead><tr><th>No</th><th>${kind==='PO'?'Uraian Jenis Bahan Baku':'Nama Barang'}</th><th>${kind==='CKL'?'Qty Krm':'Jumlah'}</th><th>Satuan</th>${kind==='CKL'?'<th>Qty Trm</th><th>Ceklis Kondisi Fisik</th>':''}<th>Keterangan</th></tr></thead><tbody>${details}</tbody></table><div class="signers">${kind==='CKL'?signer('Diserahkan Oleh (Supir / Kurir)',s.driver,{}):signer(kind==='PO'?'Penerima Pesanan,':'Penerima,',kind==='PO'?s.signatory||h.senderSignatory:s.receiverSignatory,s,kind==='PO')}${signer(kind==='PO'?'Pemesan,':kind==='SJ'?'Hormat Kami,':'Diterima Oleh (Bagian Gudang)',kind==='PO'?s.orderer:kind==='SJ'?s.signatory||h.senderSignatory:s.receiverSignatory,s,kind==='SJ')}${kind==='CKL'?signer('Mengetahui (Security / Penanggung Jawab)',s.security,s,true):''}</div>`;
  }
  return `<!doctype html><html><head><meta charset="utf-8"><title>${esc(DELIVERY_KINDS[kind])} ${esc(doc.documentNumber)}</title><style>${DELIVERY_CSS}</style></head><body><div class="toolbar"><button onclick="window.print()">Cetak / Simpan PDF</button><button onclick="document.querySelectorAll('.asset').forEach(x=>{x.style.left='0px';x.style.top='0px'})">Reset posisi aset</button><span>Klik teks untuk edit cetak. Geser gambar; tarik sudut kanan bawah untuk ukuran. Perubahan cetak tidak mengubah invoice FINAL.</span></div><main class="paper ${kind==='SJ'?'standard':''}" contenteditable="true">${kop}${body}</main><script>
(()=>{document.querySelectorAll('.asset').forEach(el=>{el.addEventListener('pointerdown',e=>{const r=el.getBoundingClientRect();if(e.clientX>r.right-20&&e.clientY>r.bottom-20)return;e.preventDefault();el.setPointerCapture(e.pointerId);const x=e.clientX,y=e.clientY,left=el.offsetLeft,top=el.offsetTop;const move=m=>{el.style.left=left+m.clientX-x+'px';el.style.top=top+m.clientY-y+'px'};const stop=()=>{el.removeEventListener('pointermove',move);el.removeEventListener('pointerup',stop)};el.addEventListener('pointermove',move);el.addEventListener('pointerup',stop)})});
const save=document.createElement('button');save.textContent='Gunakan posisi ini di halaman dokumen';save.onclick=()=>{const positions={};document.querySelectorAll('.asset').forEach(el=>{positions[el.dataset.asset]={x:el.offsetLeft,y:el.offsetTop,w:el.offsetWidth,h:el.offsetHeight}});if(window.opener)window.opener.postMessage({type:'delivery-positions',documentId:${Number(doc.id)||0},positions},location.origin);};document.querySelector('.toolbar').appendChild(save);
})();</script></body></html>`;
}
