import React,{useEffect,useState} from 'react';
import {CORE_API,readSessionToken} from '../auth/session.js';
import InvoiceRecapTable from './InvoiceRecapTable.jsx';
import OperationalItemRecap from './OperationalItemRecap.jsx';
export function currentWeek(){const now=new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Jakarta'}));now.setDate(now.getDate()-((now.getDay()+6)%7));const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const start=iso(now);now.setDate(now.getDate()+4);return{start,end:iso(now)};}
export default function InvoiceRecap({site}){
 const [period,setPeriod]=useState(currentWeek),[mode,setMode]=useState('calendar'),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 const [pickWeek,setPickWeek]=useState(false);
 useEffect(()=>{let dead=false;setRows([]);setError('');if(!period.start||!period.end||period.start>period.end){setError('Tanggal awal harus sebelum atau sama dengan tanggal akhir.');setBusy(false);return;}setBusy(true);fetch(`${CORE_API}/v1/accountant-documents/recap?${new URLSearchParams({site,start_date:period.start,end_date:period.end})}`,{headers:{Authorization:`Bearer ${readSessionToken()}`}}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(typeof b.detail==='string'?b.detail:'Gagal memuat rekap');return b;}).then(b=>{if(!dead)setRows(b.documents||[]);}).catch(e=>{if(!dead)setError(e.message);}).finally(()=>{if(!dead)setBusy(false);});return()=>{dead=true;};},[site,period.start,period.end,refresh]);
 const dates=[];if(period.start&&period.end&&period.start<=period.end){const d=new Date(period.start+'T12:00:00');for(let i=0;i<366&&d.toISOString().slice(0,10)<=period.end;i++,d.setDate(d.getDate()+1))dates.push(d.toISOString().slice(0,10));}
 return <section className="lpdh-form-section"><h2>Rekap Invoice · {site==='MAJA'?'Maja':'Cemplang'}</h2><p>Ringkasan pengeluaran per kategori. Klik tanggal untuk menyaring tabel dan klik invoice untuk popup detail, PDF, serta Dokumen Pendukung. Hanya FINAL dihitung.</p><div className="invoice-recap-filters"><label>Dari tanggal<input aria-label="Rekap dari tanggal" type="date" value={period.start} onChange={e=>{setPickWeek(false);setPeriod(p=>({...p,start:e.target.value}));}}/></label><label>Sampai tanggal<input aria-label="Rekap sampai tanggal" type="date" value={period.end} onChange={e=>{setPickWeek(false);setPeriod(p=>({...p,end:e.target.value}));}}/></label><button onClick={()=>{setPickWeek(false);setPeriod(currentWeek());}}>Minggu ini</button><button onClick={()=>setRefresh(n=>n+1)}>Muat ulang</button><button type="button" aria-pressed={mode==='items'} onClick={()=>setMode('items')}>Rekap Item Operasional</button><button aria-pressed={mode==='calendar'} onClick={()=>setMode('calendar')}>Kalender</button><button aria-pressed={mode==='list'} onClick={()=>setMode('list')}>List / Tabel</button></div>{error&&<p role="alert">{error}</p>}{mode==='items'?<OperationalItemRecap site={site} period={period} refresh={refresh}/>:busy?<p role="status">Memuat rekap…</p>:<InvoiceRecapTable rows={rows} dates={dates} site={site} mode={mode} pickWeek={pickWeek} onWeek={()=>{setPickWeek(true);setPeriod(currentWeek());}}/>}</section>;
}

