import React,{useEffect,useState,useRef} from 'react';
import {documentApi} from '../documents/documentApi.js';
import {downloadBase64} from './lpdhApi.js';
const columns=['Bahan Baku','Operasional','Upah Relawan','Guru','Kader','Insentif Mitra'];
const names={BAHAN_BAKU:'Bahan Baku',OPERASIONAL:'Operasional',UPAH_RELAWAN:'Upah / Insentif',INSENTIF_GURU_KADER:'Insentif Guru & Kader',INSENTIF_MITRA:'Insentif Mitra'};
const money=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
export function amounts(d){const a=Object.fromEntries(columns.map(k=>[k,0]));if(d.documentType==='UPAH_RELAWAN'||d.documentType==='INSENTIF_GURU_KADER'){for(const x of d.items||[]){const t=x.metadata?.recipientType;a[t==='Guru'?'Guru':t==='Kader'?'Kader':'Upah Relawan']+=Number(x.lineTotal||0);}if(!(d.items||[]).length)a[d.documentType==='UPAH_RELAWAN'?'Upah Relawan':'Guru']=Number(d.total||0);}else a[names[d.documentType]||'Operasional']=Number(d.total||0);return a;}
export default function InvoiceRecapTable({rows,dates,site,mode,onWeek,pickWeek}){
 const [day,setDay]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState('FINAL'),[checked,setChecked]=useState([]),[detail,setDetail]=useState(null),[pdf,setPdf]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setDay('');setChecked(pickWeek?rows.filter(d=>d.status==='FINAL').map(d=>d.id):[]);setDetail(null);},[rows,site,pickWeek]);
 useEffect(()=>{setPdf('');setError('');},[detail?.id,site]);
 useEffect(()=>()=>{if(pdf)URL.revokeObjectURL(pdf);},[pdf]);
 useEffect(()=>{if(!detail)return;const close=e=>{if(e.key==='Escape')setDetail(null);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[detail]);
 const detailRef=useRef(null);detailRef.current=detail;
 const filtered=rows.filter(d=>(!day||d.serviceDate===day)&&(!status||d.status===status)&&(!category||amounts(d)[category]>0));
 const selected=filtered.filter(d=>!checked.length||checked.includes(d.id)),finals=selected.filter(d=>d.status==='FINAL');
 const totals=Object.fromEntries(columns.map(k=>[k,finals.reduce((s,d)=>s+amounts(d)[k],0)])),total=finals.reduce((s,d)=>s+Number(d.total||0),0);
 const filter=fn=>{setChecked([]);fn();};
 const action=async(kind)=>{const id=detail.id;setBusy(true);setError('');try{const r=await(kind==='excel'?documentApi.excel(id):documentApi.pdf(id));if(detailRef.current?.id!==id)return;if(kind==='preview'){const bytes=Uint8Array.from(atob(r.contentBase64),c=>c.charCodeAt(0));setPdf(URL.createObjectURL(new Blob([bytes],{type:r.mimeType})));}else downloadBase64(r.filename,r.mimeType,r.contentBase64);}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <><div className="invoice-recap-filters"><label>Kategori<select aria-label="Filter kategori rekap" value={category} onChange={e=>filter(()=>setCategory(e.target.value))}><option value="">Semua kategori</option>{columns.map(k=><option key={k}>{k}</option>)}</select></label><label>Status<select aria-label="Filter status rekap" value={status} onChange={e=>filter(()=>setStatus(e.target.value))}><option value="FINAL">FINAL</option><option value="">Semua status</option><option>DRAFT</option><option value="CANCELLED">Dibatalkan</option></select></label><button onClick={()=>{setStatus('FINAL');setCategory('');setDay('');setChecked(rows.filter(d=>d.status==='FINAL').map(d=>d.id));onWeek();}}>Pilih minggu ini semua</button></div>
 {mode==='calendar'&&<div className="invoice-recap-calendar">{dates.map(date=><section key={date}><button aria-pressed={day===date} onClick={()=>filter(()=>setDay(day===date?'':date))}>{new Date(date+'T12:00:00').toLocaleDateString('id-ID',{weekday:'short',day:'numeric',month:'short'})}</button>{rows.filter(d=>d.serviceDate===date&&(!status||d.status===status)&&(!category||amounts(d)[category]>0)).map(d=><button type="button" className={`invoice-recap-card ${d.status.toLowerCase()}`} key={d.id} onClick={()=>setDetail(d)}><strong>{d.documentNumber}</strong><span>{names[d.documentType]}</span><span>{money(d.total)}</span><small>{d.status==='CANCELLED'?'DIBATALKAN':d.status}</small></button>)}</section>)}</div>}
 <div className="invoice-recap-filters">{day&&<button onClick={()=>filter(()=>setDay(''))}>Hapus filter tanggal {day}</button>}<button onClick={()=>setChecked(filtered.map(d=>d.id))}>Pilih semua hasil filter</button><button onClick={()=>setChecked([])}>Hapus ceklis</button><span>{checked.length?'Pilihan ceklis':'Seluruh hasil filter'} · {selected.length} invoice · Total FINAL <strong>{money(total)}</strong></span></div>
 <div className="invoice-recap-totals">{columns.map(k=><div key={k}><small>{k}</small><strong>{money(totals[k])}</strong></div>)}</div>
 <div className="invoice-recap-table-wrap"><table className="invoice-recap-table"><thead><tr><th>Pilih</th><th>Tanggal</th><th>Nomor invoice</th><th>Status</th>{columns.map(k=><th key={k}>{k}</th>)}<th>Total</th></tr></thead><tbody>{filtered.map(d=><tr key={d.id}><td><input type="checkbox" aria-label={`Pilih rekap ${d.documentNumber} ${d.id}`} checked={checked.includes(d.id)} onChange={e=>setChecked(ids=>e.target.checked?[...ids,d.id]:ids.filter(id=>id!==d.id))}/></td><td>{d.serviceDate}</td><td><button onClick={()=>setDetail(d)}>{d.documentNumber}</button></td><td>{d.status==='CANCELLED'?'DIBATALKAN':d.status}</td>{columns.map(k=><td key={k}>{amounts(d)[k]?money(amounts(d)[k]):'—'}</td>)}<td>{money(d.total)}</td></tr>)}</tbody><tfoot><tr><th colSpan="4">TOTAL FINAL {checked.length?'TERPILIH':'HASIL FILTER'}</th>{columns.map(k=><th key={k}>{money(totals[k])}</th>)}<th>{money(total)}</th></tr></tfoot></table></div>{!filtered.length&&<p>Belum ada invoice sesuai filter.</p>}
 {detail&&<div className="invoice-recap-overlay"><section role="dialog" aria-modal="true" aria-label="Detail invoice rekap" className="invoice-recap-dialog"><header><h3>{detail.documentNumber}</h3><button autoFocus onClick={()=>setDetail(null)}>Tutup detail</button></header><p>{detail.serviceDate} · {names[detail.documentType]} · <strong>{money(detail.total)}</strong> · {detail.status}</p>{detail.status==='FINAL'?<><p>Dasar data harian</p><p>{detail.driveUri&&detail.driveExcelUri?'PDF + Excel tersimpan di Drive':detail.driveUri?'PDF tersimpan; Excel belum diarsipkan':'Arsip Drive belum lengkap'}</p></>:<p>{detail.status==='CANCELLED'?'Dokumen dibatalkan — tidak dihitung sebagai pengeluaran.':'DRAFT — belum menjadi dasar data harian.'}</p>}{detail.driveUploadError&&<p role="alert">{detail.driveUploadError}</p>}<div className="invoice-recap-filters"><button disabled={busy} onClick={()=>action('preview')}>Preview PDF</button><button disabled={busy} onClick={()=>action('pdf')}>Unduh PDF</button><button disabled={busy} onClick={()=>action('excel')}>Unduh Excel</button>{detail.driveUri&&<a href={detail.driveUri} target="_blank" rel="noopener noreferrer">PDF di Drive</a>}{detail.driveExcelUri&&<a href={detail.driveExcelUri} target="_blank" rel="noopener noreferrer">Excel di Drive</a>}{detail.status==='FINAL'&&['BAHAN_BAKU','OPERASIONAL'].includes(detail.documentType)&&<a href={`/delivery?site=${site}&date=${detail.serviceDate}&document=${detail.id}`} target="_blank" rel="noopener noreferrer">Dokumen Pendukung</a>}</div>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">Memuat dokumen…</p>}{pdf&&<><iframe title="Preview PDF invoice rekap" src={pdf}/><a href={pdf} target="_blank" rel="noopener noreferrer">Buka preview PDF di tab baru</a></>}<table><thead><tr><th>Item / penerima</th><th>Jumlah</th></tr></thead><tbody>{detail.items?.map((x,i)=><tr key={i}><td>{x.itemName}</td><td>{money(x.lineTotal)}</td></tr>)}</tbody></table></section></div>}
 </>;
}

