import React,{useEffect,useState} from 'react';
import {CORE_API,readSessionToken} from '../auth/session.js';
export function currentWeek(){const now=new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Jakarta'}));now.setDate(now.getDate()-((now.getDay()+6)%7));const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const start=iso(now);now.setDate(now.getDate()+4);return{start,end:iso(now)};}
const names={BAHAN_BAKU:'Bahan Baku',OPERASIONAL:'Operasional',UPAH_RELAWAN:'Upah Relawan',INSENTIF_GURU_KADER:'Upah / Insentif Guru & Kader',INSENTIF_MITRA:'Insentif Mitra'};
const money=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
export default function InvoiceRecap({site,onOpen}){
 const [period,setPeriod]=useState(currentWeek),[mode,setMode]=useState('calendar'),[rows,setRows]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
 useEffect(()=>{let dead=false;setRows([]);setError('');if(!period.start||!period.end||period.start>period.end){setError('Tanggal awal harus sebelum atau sama dengan tanggal akhir.');setBusy(false);return;}setBusy(true);fetch(`${CORE_API}/v1/accountant-documents/recap?${new URLSearchParams({site,start_date:period.start,end_date:period.end})}`,{headers:{Authorization:`Bearer ${readSessionToken()}`}}).then(async r=>{const b=await r.json();if(!r.ok)throw Error(typeof b.detail==='string'?b.detail:'Gagal memuat rekap');return b;}).then(b=>{if(!dead)setRows(b.documents||[]);}).catch(e=>{if(!dead)setError(e.message);}).finally(()=>{if(!dead)setBusy(false);});return()=>{dead=true;};},[site,period.start,period.end,refresh]);
 const dates=[];if(period.start&&period.end&&period.start<=period.end){const d=new Date(period.start+'T12:00:00');for(let i=0;i<366&&d.toISOString().slice(0,10)<=period.end;i++,d.setDate(d.getDate()+1))dates.push(d.toISOString().slice(0,10));}
 const card=d=><button type="button" className={`invoice-recap-card ${d.status.toLowerCase()}`} key={d.id} onClick={()=>onOpen(d.serviceDate)}><strong>{d.documentNumber}</strong><span>{names[d.documentType]||d.documentType}</span><span>{money(d.total)}</span><small>{d.status==='CANCELLED'?'DIBATALKAN':d.status}</small></button>;
 return <section className="lpdh-form-section"><h2>Rekap Invoice · {site==='MAJA'?'Maja':'Cemplang'}</h2><p>Default Senin–Jumat minggu berjalan. Klik invoice untuk membuka dokumen pada tanggalnya. Total hanya dari dokumen FINAL; DRAFT dan pembatalan tidak dijumlahkan.</p><div className="invoice-recap-filters"><label>Dari tanggal<input aria-label="Rekap dari tanggal" type="date" value={period.start} onChange={e=>setPeriod(p=>({...p,start:e.target.value}))}/></label><label>Sampai tanggal<input aria-label="Rekap sampai tanggal" type="date" value={period.end} onChange={e=>setPeriod(p=>({...p,end:e.target.value}))}/></label><button onClick={()=>setPeriod(currentWeek())}>Minggu ini</button><button onClick={()=>setRefresh(n=>n+1)}>Muat ulang</button><button aria-pressed={mode==='calendar'} onClick={()=>setMode('calendar')}>Kalender</button><button aria-pressed={mode==='list'} onClick={()=>setMode('list')}>List</button></div>{error&&<p role="alert">{error}</p>}{busy?<p role="status">Memuat rekap…</p>:<><p><strong>{rows.length} dokumen · Total FINAL {money(rows.filter(d=>d.status==='FINAL').reduce((s,d)=>s+Number(d.total||0),0))}</strong></p>{mode==='calendar'?<div className="invoice-recap-calendar">{dates.map(date=><section key={date}><h3>{new Date(date+'T12:00:00').toLocaleDateString('id-ID',{weekday:'short',day:'numeric',month:'short'})}</h3>{rows.filter(d=>d.serviceDate===date).map(card)}{!rows.some(d=>d.serviceDate===date)&&<small>Tidak ada invoice</small>}</section>)}</div>:<div className="invoice-recap-list">{rows.map(d=><div key={d.id}><small>{d.serviceDate}</small>{card(d)}</div>)}</div>}{!rows.length&&!error&&<p>Belum ada invoice pada periode ini.</p>}</>}</section>;
}

