import React,{useEffect,useRef,useState} from 'react';
import {arrayBufferToBase64} from './lpdhApi.js';

const labels={sppgName:'Nama SPPG',foundation:'Nama Yayasan / kop',headName:'Nama Kepala SPPG',foundationName:'Nama penerima / pengurus Yayasan',address:'Alamat pada kop',payer:'Sudah terima dari',purpose:'Untuk pembayaran'};
const images={letterhead:'Kop / logo',headSignature:'TTD Kepala SPPG',headStamp:'Stempel SPPG',foundationSignature:'TTD penerima Yayasan',foundationStamp:'Stempel Yayasan'};
const moneyLabels={rawAmount:'Nilai bahan baku (Rp)',operationalAmount:'Nilai operasional (Rp)',incentiveAmount:'Nilai insentif (Rp)'};
function splitTotal(value){if(!/^\d+$/.test(String(value))||Number(value)>=1e15)return null;const t=BigInt(value),raw=(t*67n+50n)/100n,inc=(t*13n+50n)/100n;return{rawAmount:Number(raw),incentiveAmount:Number(inc),operationalAmount:Number(t-raw-inc)}}
export default function TopupReceiptActions({site,serviceDate,row,index,api,disabled,onData,isNew=false}){
 const[open,setOpen]=useState(false),[profile,setProfile]=useState({}),[number,setNumber]=useState(''),[receipt,setReceipt]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[url,setUrl]=useState(''),[hash,setHash]=useState('');
 const alive=useRef(true),lock=useRef(false),pdfUrl=useRef('');
 const[funds,setFunds]=useState(row);
 const[totalInput,setTotalInput]=useState('0');const boundRow=useRef(row),boundIndex=useRef(index);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;if(pdfUrl.current)URL.revokeObjectURL(pdfUrl.current)}},[]);
 const dirty=!!receipt&&(receipt.documentNumber!==number||JSON.stringify(receipt.snapshot.profile)!==JSON.stringify(profile)||JSON.stringify(receipt.snapshot.funds||row)!==JSON.stringify(funds));
 const run=async(fn)=>{if(lock.current)return;lock.current=true;setBusy(true);setMessage('');try{await fn()}catch(e){if(alive.current)setMessage(e.message)}finally{lock.current=false;if(alive.current)setBusy(false)}};
 const load=()=>{boundRow.current=row;boundIndex.current=index;setOpen(true);run(async()=>{const r=await api.topupReceipts(site,serviceDate);if(!alive.current)return;const found=r.receipts.find(x=>x.id===row._topupReceiptId);const f=found?.snapshot.funds||row;setReceipt(found||null);setFunds(f);setTotalInput(String(Object.keys(moneyLabels).reduce((s,k)=>s+Number(f[k]||0),0)));setProfile(found?.snapshot.profile||r.profile);setNumber(found?.status==='CANCELLED'?r.documentNumber:found?.documentNumber||r.documentNumber);setHash('');setUrl('')})};
 const edit=(key,value)=>{setProfile(p=>({...p,[key]:value}));setHash('');setUrl('')};
 const image=async(key,file)=>{if(!file)return;try{if(file.size>5*1024*1024)throw Error('Gambar maksimal 5 MB.');if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Pilih PNG, JPG, atau WebP.');edit(key,`data:${file.type};base64,${arrayBufferToBase64(await file.arrayBuffer())}`)}catch(e){setMessage(e.message)}};
 const save=()=>run(async()=>{if(!splitTotal(totalInput)||Number(totalInput)<=0)throw Error('Isi total TopUp berupa rupiah bulat lebih dari nol.');const r=await api.topupReceiptDraft({site,service_date:serviceDate,row_index:boundIndex.current,expected_funds:boundRow.current,funds,total_amount:totalInput,document_number:number,profile});if(!alive.current)return;setReceipt(r.receipt);setFunds(r.receipt.snapshot.funds||funds);setProfile(r.receipt.snapshot.profile);setNumber(r.receipt.documentNumber);setHash('');setUrl('');onData(r.data,r.receipt.id);boundRow.current=r.data.topups.find(x=>x._topupReceiptId===r.receipt.id)||boundRow.current;setMessage('Draft tersimpan. Buka preview sebelum Finalkan. Nilai masuk ke penerimaan TopUp setelah FINAL, bukan saat menyimpan draft.')});
 const preview=()=>run(async()=>{const r=await api.topupReceiptPdf(receipt.id);if(!alive.current)return;if(pdfUrl.current)URL.revokeObjectURL(pdfUrl.current);pdfUrl.current=URL.createObjectURL(new Blob([Uint8Array.from(atob(r.contentBase64),c=>c.charCodeAt(0))],{type:'application/pdf'}));setUrl(pdfUrl.current);setHash(r.hash)});
 const finalize=()=>{if(!window.confirm('Finalkan kuitansi TopUp ini? PDF disimpan ke Drive, nomor dan link masuk ke baris penerimaan. Ini bukan konfirmasi transfer bank.'))return;run(async()=>{const r=await api.topupReceiptFinalize(receipt.id,hash);if(!alive.current)return;setReceipt(r.receipt);onData(r.data,r.receipt.id);boundRow.current=r.data.topups.find(x=>x._topupReceiptId===r.receipt.id)||boundRow.current;setUrl('');setHash('');setMessage('FINAL: PDF tersimpan di Drive. Nilai, nomor dan link otomatis terisi. Klik Simpan & Validasi untuk memperbarui pemeriksaan.')})};
 const cancel=()=>{const reason=window.prompt('Alasan membatalkan kuitansi? Arsip Drive tetap disimpan.');if(!reason?.trim())return;run(async()=>{const r=await api.topupReceiptCancel(receipt.id,receipt.hash,reason);if(!alive.current)return;setReceipt(r.receipt);onData(r.data,r.receipt.id);boundRow.current=r.data.topups.find(x=>x._topupReceiptId===r.receipt.id)||boundRow.current;setHash('');setUrl('');setMessage('Dibatalkan. Dana penerimaan tidak dihapus; link otomatis dilepas. Simpan & Validasi atau buat draft baru.')})};
 const total=['rawAmount','operationalAmount','incentiveAmount'].reduce((s,k)=>s+Number(funds[k]||0),0);
 return <div><button type="button" disabled={disabled&&!row._topupReceiptId} onClick={load}>{isNew?'Buat Kuitansi TopUp baru':`Buat / Buka Kuitansi TopUp ${index+1}`}</button>
 {disabled&&!row._topupReceiptId&&<small> Klik Simpan &amp; Validasi dahulu.</small>}
 {open&&<div className="invoice-recap-overlay"><section className="invoice-recap-dialog topup-receipt-dialog" role="dialog" aria-modal="true" aria-label="Kuitansi penerimaan TopUp">
 <header><h3>Kuitansi TopUp · format Banper</h3><button type="button" disabled={busy} onClick={()=>setOpen(false)}>Tutup</button></header>
 <p>Tanggal penerimaan {funds.date} · Total Rp {total.toLocaleString('id-ID')} · {receipt?.status||'Belum ada draft'}</p>
 <fieldset><legend>Nilai penerimaan TopUp</legend><div className="lpdh-form-grid"><label>Tanggal penerimaan<input type="date" value={funds.date||''} disabled={busy||receipt?.status==='FINAL'} onChange={e=>{setFunds({...funds,date:e.target.value});setHash('');setUrl('')}}/></label><label>Referensi SP2D / transfer<input value={funds.reference||''} disabled={busy||receipt?.status==='FINAL'} onChange={e=>{setFunds({...funds,reference:e.target.value});setHash('');setUrl('')}}/></label><label>Total TopUp (Rp)<input type="number" min="1" step="1" value={totalInput} disabled={busy||receipt?.status==='FINAL'} onChange={e=>{const v=e.target.value;setTotalInput(v);const split=splitTotal(v);if(split)setFunds({...funds,...split});setHash('');setUrl('')}}/></label></div><p>Pembagian otomatis saat simpan: bahan baku 67%, insentif 13%, operasional 20%. Pembulatan rupiah disesuaikan di operasional agar jumlah tepat.</p><div className="lpdh-form-grid">{Object.entries(moneyLabels).map(([key,label])=><div key={key}>{label}<strong style={{display:'block'}}>Rp {Number(funds[key]||0).toLocaleString('id-ID')}</strong></div>)}</div><strong>Total Rp {total.toLocaleString('id-ID')}</strong><p>Nilai menggantikan baris TopUp ini saat FINAL, tidak membuat penerimaan tambahan. Kuitansi lama yang sudah FINAL tetap mengikuti nilai tersimpannya.</p></fieldset>
 <p>Ini bukti dana masuk, bukan invoice pengeluaran. Kop dan kedua penandatangan dapat diisi; isian awal mengikuti master.</p>
 <label>Nomor kuitansi<input value={number} disabled={busy||receipt?.status==='FINAL'} onChange={e=>{setNumber(e.target.value);setHash('');setUrl('')}}/></label>
 <div className="lpdh-form-grid">{Object.entries(labels).map(([key,label])=><label key={key}>{label}<input value={profile[key]||''} disabled={busy||receipt?.status==='FINAL'} onChange={e=>edit(key,e.target.value)}/></label>)}</div>
 <div className="lpdh-form-grid">{Object.entries(images).map(([key,label])=><label key={key}>{label}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy||receipt?.status==='FINAL'} onChange={e=>{image(key,e.target.files?.[0]);e.target.value=''}}/>{profile[key]&&<><img src={profile[key]} alt={label} style={{maxWidth:160,maxHeight:85,objectFit:'contain'}}/><button type="button" disabled={busy||receipt?.status==='FINAL'} onClick={()=>edit(key,'')}>Hapus gambar</button></>}</label>)}</div>
 <div className="lpdh-inline-actions">{receipt?.status!=='FINAL'&&<button type="button" disabled={busy} onClick={save}>Simpan Draft Kuitansi</button>}
 <button type="button" disabled={busy||!receipt||dirty||receipt.status==='CANCELLED'} onClick={preview}>Preview / Cetak PDF</button>
 {receipt?.status==='DRAFT'&&<button type="button" disabled={busy||dirty||!hash} onClick={finalize}>Finalkan &amp; Simpan ke Drive</button>}
 {receipt&&receipt.status!=='CANCELLED'&&<button type="button" disabled={busy} onClick={cancel}>Batalkan Kuitansi</button>}
 {receipt?.pdfLink&&<a href={receipt.pdfLink} target="_blank" rel="noopener noreferrer">PDF di Drive</a>}
 {url&&<a href={url} target="_blank" rel="noopener noreferrer">Buka PDF untuk cetak / unduh</a>}</div>
 {message&&<p role="status">{message}</p>}{url&&<iframe title="Preview Kuitansi TopUp" src={url}/>}
 </section></div>}</div>;
}

